name: hackernews-daily

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 2 */10 * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Generation
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 10
          retry_wait_seconds: 30
          command: uv run generate.py

      - uses: stefanzweifel/git-auto-commit-action@v5

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify -d _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
